schema {
  query: Query
}

scalar Date

type User {
  id: ID!
  firstname: String
  lastname: String
  email: String
  password: String
  dob: Date
  createdAt: Date
  updatedAt: Date
}

type Query {
  getUsers: [User]
}
